// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingLoadAnalyzer.Infrastructure.Persistence;

#nullable disable

namespace TrainingLoadAnalyzer.Infrastructure.Migrations
{
    [DbContext(typeof(ImportDbContext))]
    [Migration("20260917112659_InitialConnection")]
    partial class InitialConnection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TrainingLoadAnalyzer.Infrastructure.Persistence.StravaConnection", b =>
                {
                    b.Property<long>("AthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ConnectedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrantedScopes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AthleteId");

                    b.ToTable("Connections");
                });
#pragma warning restore 612, 618
        }
    }
}
