// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingLoadAnalyzer.Infrastructure.Persistence;

#nullable disable

namespace TrainingLoadAnalyzer.Infrastructure.Migrations
{
    [DbContext(typeof(ImportDbContext))]
    partial class ImportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TrainingLoadAnalyzer.Infrastructure.Persistence.ActivityRow", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeartRateJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HeartRateOutstanding")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MovingTimeTicks")
                        .HasColumnType("INTEGER");

                    b.Property<short>("StartedAtOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Provider", "ExternalId");

                    b.HasIndex("StartedAtUtcTicks");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("TrainingLoadAnalyzer.Infrastructure.Persistence.StravaConnection", b =>
                {
                    b.Property<long>("AthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ConnectedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrantedScopes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AthleteId");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("TrainingLoadAnalyzer.Infrastructure.Persistence.SyncState", b =>
                {
                    b.Property<long>("AthleteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastOutcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSyncStartedAtUtcTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResumePointUtcTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("AthleteId");

                    b.ToTable("SyncStates");
                });
#pragma warning restore 612, 618
        }
    }
}
