using System.Net;

namespace TrainingLoadAnalyzer.Infrastructure.Tests.Fakes;

/// <summary>
///   Stands in for Strava. Hand-written rather than generated by a mocking library, because the
///   behaviour under test lives as much in response <em>headers</em> as in bodies — the rate-limit
///   handling of user story 4 reads nothing else (research R9, R16).
/// </summary>
/// <remarks>
///   Records every request it was given, so a test can assert on <em>what was asked for</em> and not
///   only on what came back. Several requirements — FR-027's incremental request and FR-017a's
///   suppressed stream call — are statements about the request, and are untestable otherwise.
/// </remarks>
internal sealed class StubHttpMessageHandler : HttpMessageHandler
{
    private readonly List<Rule> rules = [];

    /// <summary>Every request this handler was asked to send, in order.</summary>
    public List<HttpRequestMessage> Requests { get; } = [];

    /// <summary>Responds to any request whose URI contains <paramref name="uriFragment"/>.</summary>
    public StubHttpMessageHandler Respond(
        string uriFragment,
        HttpStatusCode status,
        string? json = null,
        IReadOnlyDictionary<string, string>? headers = null,
        bool once = false)
    {
        rules.Add(new Rule(uriFragment, status, json, headers, once));

        return this;
    }

    /// <summary>
    ///   Like <see cref="Respond"/>, but takes precedence over rules already added. Rules are
    ///   matched in order, so a specific URL must be registered ahead of a general one.
    /// </summary>
    public StubHttpMessageHandler RespondFirst(
        string uriFragment,
        HttpStatusCode status,
        string? json = null,
        IReadOnlyDictionary<string, string>? headers = null,
        bool once = false)
    {
        rules.Insert(0, new Rule(uriFragment, status, json, headers, once));

        return this;
    }

    /// <summary>Fails the matching request as a dropped connection, for FR-037 and C61.</summary>
    public StubHttpMessageHandler Drop(string uriFragment, bool once = false)
    {
        rules.Add(new Rule(uriFragment, null, null, null, once));

        return this;
    }

    /// <summary>
    ///   Held open, every request waits on it. Lets a test keep one sync in flight while starting a
    ///   second, which is the only way to exercise FR-040 deterministically.
    /// </summary>
    public TaskCompletionSource? Gate { get; set; }

    protected override async Task<HttpResponseMessage> SendAsync(
        HttpRequestMessage request,
        CancellationToken cancellationToken)
    {
        Requests.Add(request);

        if (Gate is not null)
        {
            await Gate.Task;
        }

        var uri = request.RequestUri?.ToString() ?? string.Empty;
        var rule = rules.FirstOrDefault(r => !r.Spent && uri.Contains(r.UriFragment, StringComparison.Ordinal));

        if (rule is null)
        {
            throw new InvalidOperationException(
                $"The stub has no rule for '{uri}'. A request the test did not anticipate is a "
                    + "failure of the test, not a case to be defaulted.");
        }

        if (rule.Once)
        {
            rule.Spent = true;
        }

        if (rule.Status is null)
        {
            throw new HttpRequestException($"Connection dropped (stubbed) for '{uri}'.");
        }

        var response = new HttpResponseMessage(rule.Status.Value)
        {
            Content = new StringContent(rule.Json ?? "{}", System.Text.Encoding.UTF8, "application/json"),
        };

        foreach (var (name, value) in rule.Headers ?? new Dictionary<string, string>())
        {
            response.Headers.TryAddWithoutValidation(name, value);
        }

        return response;
    }

    private sealed record Rule(
        string UriFragment,
        HttpStatusCode? Status,
        string? Json,
        IReadOnlyDictionary<string, string>? Headers,
        bool Once)
    {
        public bool Spent { get; set; }
    }
}
